# Pipeline para POC Azure tribu Public Cloud

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  location: 'southcentralus'
  rgName: 'pocPipelineRG'
  # Estas variables se tienen que personalizar de acuerdo a la cuenta de Azure y Docker Hub
  azSubscription: 'ef433f0c-80ed-447e-ae0c-0f38b7e6125d'
  usuarioDockerHub: 'gaboverriding'
  repoDockerHub: 'api-rest-incidencias'
  conexionDockerHub: 'gaboDockerHub'
  azureResourceManagerConnection: 'pocPipelineRG'

stages:
- stage: Build
  displayName: Construcción de Imagen en Azure
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    # Construir imagen de API en infraestructura de Azure
    - task: Docker@2
      displayName: Construye imagen de API en Azure
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/SourceCode/Dockerfile'        
        repository: '$(usuarioDockerHub)/$(repoDockerHub)'
        tags: $(tag)

    # Disponibilizar imagen en Docker Hub
    - task: Docker@2
      displayName: Disponibilizar imagen de API en Docker Hub
      inputs:
        containerRegistry: '$(conexionDockerHub)'
        repository: '$(usuarioDockerHub)/$(repoDockerHub)'
        command: push
        tags: $(tag)

    # Copiar ARM template
    - task: CopyFiles@2
      displayName: 'Copiar ARM templates'
      inputs:
        SourceFolder: ARMWebAppTemplates
        TargetFolder: '$(build.artifactstagingdirectory)/ARMWebAppTemplates'

    # Publicar artefactos
    - task: PublishBuildArtifacts@1
      displayName: 'Publicar Artefactos'

    # Crear WebApp Container para la API
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: Azure WebApp for Container para API Rest de Incidencias'
      inputs:
        azureResourceManagerConnection: '$(azureResourceManagerConnection)'
        subscriptionId: '$(azSubscription)'
        resourceGroupName: '$(rgName)'
        location: '$(location)'
        csmFile: '$(build.artifactstagingdirectory)/ARMWebAppTemplates/webapp_template.json'
        csmParametersFile: '$(build.artifactstagingdirectory)/ARMWebAppTemplates/webapp_parameters.json'
